# docker-compose.yml
version: "3.9"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - 5432:5432
